### ISSUE TITLE
Out of date values in neo4j-index-relationship documents

### ISSUE THREAD

**Issue by foobargeez** [graphaware/neo4j-to-elasticsearch#39]
First, thanks for your work on implementing getStartNode() and getEndNode() -- it's been immensely useful for us.  We store a few properties from start and end nodes connecting a given relationship in ES so to help us with some aggregations.  This is working great except that the stored properties from start and end nodes don't get automatically updated in relationship index when the nodes are updated.  This is resulting in out of date values.

As an example, we have the following defined in our `relationship_mappings` and once the document in relationship index is created, the value isn't updated when the EndNode is updated with new labels.

`"endNodeLabels": "getEndNode().getLabels()"`

This could be out of scope for you but I want to run it by you to see if you have plans of addressing it.  The other option for us is to not store any properties from start/end nodes in relationship index that we think will change in future (that is pretty much everything except UUID I suppose, sadly) and rely on another neo4j/ES query to retrieve the document properties that are of interest.  It can be done but it's another hop that I am trying to avoid if I can and want to see if this is an easy fix on the connector end.

Thanks much!

**Comment by bachmanm** [comment]
Hi,

this is by design and I don't think we can change how it works - the performance implications could be huge. The framework only ever triggers updates on the nodes/relationships that have actually changed, not connected items. What you want is to trigger a relationship update when one of its nodes have been updated. Imagine if the node had 100k relationships!

You could work around this in your application in the following way - every time you change a node's labels, set some dummy property (could be a counter for example) on every relationship connected to the changed node which you want to update in ES... That would trigger an update. Would that work?

**Comment by foobargeez** [comment]
Thanks and I understand the performance hit for highly connected nodes.  We will deal with this in our application.

Apprecitate it!
