### ISSUE TITLE
Enable using neo4j-to-elasticsearch without the UUID plugin

### ISSUE THREAD

**Issue by davidrapin** [graphaware/neo4j-to-elasticsearch#7]
In some cases, suing UUIDs is not an option:
- UUIDs are only applied to newly created nodes (and relationships)
- some use-cases involve a huge existing Neo4j database that cannot be re-created in order to generate UUIDs

Would you consider adding an option to enable using native Neo4j IDs in ElasticSearch?

**Comment by bachmanm** [comment]
Unfortunately not I'm afraid, this is a super bad practice which we don't want to promote. What happens if a node ID is recycled in Neo4j and (for some reason, let's say because it is down), Elasticsearch does not know about it?* Then your index is pointing to a completely different node.

The UUID plugin provides a way to assign UUIDs to all nodes (and relationships, if you wish) in an existing database. Even if it is huge, it should be a matter of minutes as we try to do it efficiently.

(*) We handle this case as long as Neo4j does not go down as well

**Comment by davidrapin** [comment]
Ok, fair enough if creating UUIDs is fast.
