### ISSUE TITLE
What is the correct function to query node label under "type" in mapping.json

### ISSUE THREAD

**Issue by Zhenshan-Jin** [graphaware/neo4j-to-elasticsearch#97]
Hi,

As the title said, I tried the following script to get node/relationship label under `type`
```
{
  "defaults": {
    "key_property": "uuid",
    "nodes_index": "default-index-node",
    "relationships_index": "default-index-relationship",
    "include_remaining_properties": true
  },
  "node_mappings": [
    {
      "condition": "allNodes()",
      "type": "getLabels()"
    }
  ],
  "relationship_mappings": [
    {
      "condition": "allRelationships()",
      "type": "getType()"
    }
  ]
}
```
It works for relationship, but not node, for which the `_type` part will only display something like `[Ljava.lang.String;@75c47cea`
![mapping](https://user-images.githubusercontent.com/14370804/34701951-ab68006c-f4b0-11e7-8a2f-b9240d2f601b.png)
I'm wondering do I have some misunderstanding of the `getLabels()` funtion? 

Thanks!

BTW, where can I have a full list of function that I can use in mapping.json, I find two sources, but seems they are not complete:
https://github.com/graphaware/neo4j-framework/tree/master/common#inclusion-policies
https://github.com/graphaware/neo4j-to-elasticsearch/blob/master/docs/json-mapper.md

Zhenshan

**Comment by ikwattro** [comment]
Hi @Zhenshan-Jin 

Since node can have multiple labels, the `getLabels()` method returns an array of Strings, which does not seem compatible to be used as a ES index type.

If you are sure that nodes will only have one and only one label, you could try with `getLabels()[0]`.

Regarding the list of functions, this is hard to do because it allows standard java calls as well as specific operations on nodes and relationships such as getLabels, for the java part you can refer to the Spring Expressions documentation.
